# -------------------------
#  __  __  __   __  ______
# |  \/  | \ \ / / |  ____|
# | \  / |  \ V /  | |__
# | |\/| |   > <   |  __|
# | |  | |  / . \  | |____
# |_|  |_| /_/ \_\ |______|
# -------------------------
# MXE V.1.3.3 Configuration File

# Configuration of custom and command messages
messages:
  # Sets the language the plugin uses when communicating to the player.
  # The following languages are currently supported:
  # English, German
  # Default: en
  language: "en"

  # For setting custom messages in the future.
  # Some things don't change anything yet.
  custom:

    # Message when a player joins the server.
    # Set player as %p. Note that you will have to reset the color because of the prefix.
    join: "&9&l[join/leave]: %p&r&9 joined the server!"

    # Message when a player quits the server.
    # Set player as %p. Note that you will have to reset the color because of the prefix.
    quit: "&9&l[join/leave]: %p&r&9 left the server!"

    # Message when a player sends a message in the chat
    # Set player as %p. Note that you will have to reset the color because of the prefix.
    # Set message as %m.
    chat: "%p&r&6 says: %m"

    # Ban messages
    ban:
      # Message a player gets when they get banned
      banned:
        temporary:
          # Set player as %p.
          # Set staff as %m. Note that you will have to reset the color because of the prefix.
          # Set time as %t.
          # Set reason as %r.
          reason:
            player: "&4You have been banned for %t from this server by %m&r&4! Reason: %r"
            staff: "&eYou banned %p for %t from this server. Reason: %r"
          no-reason:
            player: "&4You have been banned for %t from this server by %m&r&4!"
            staff: "&eYou banned %p for %t from this server."
        permanent:
          # Set player as %p.
          # Set staff as %m. Note that you will have to reset the color because of the prefix.
          # Set reason as %r.
          reason:
            player: "&4You have been &lpermanently&r&4 banned from this server by %m&r&4! Reason: %r"
            staff: "&eYou permanently banned %p from this server. Reason: %r"
          no-reason:
            player: "&4You have been &lpermanently&r&4 banned from this server by %m&r&4!"
            staff: "&eYou permanently banned %p from this server."

      # Message a banned player gets when they try to join the server
      banned-join:
        temporary:
          # Set date as %d.
          # Set reason as %r.
          reason: "&4You have been banned from this server! (Expires %d) Reason: %r"
          no-reason: "&4You have been banned from this server! (Expires %d)"

        permanent:
          # Set reason as %r.
          reason: "&4You have been &lpermanently&r&4 banned from this server! Reason: %r"
          no-reason: "&4You have been &lpermanently&r&4 banned from this server!"

    # Message a player gets when he is kicked
    kick:
      # Set player as %p. Note that you will have to reset the color because of the prefix.
      # Set staff as %m. Note that you will have to reset the color because of the prefix.
      # Set reason as %r.
      reason:
        player: "&4You have been kicked from this server by %m&r&4! Reason: %r"
        staff: "&eYou kicked %p&r&e from this server. Reason: %r"
      no-reason:
        player: "&4You have been kicked from this server by %m&r&4!"
        staff: "&eYou kicked %p&r&e from this server."

    # Mute messages
    mute:
      # Message a player gets when he gets muted by a staff member
      muted:
        # Set mutetime as %t
        # Set staff as %m. Note that you will have to reset the color because of the prefix.
        # Set player as %p. Note that you will have to reset the color because of the prefix.
        temporary:
          player: "&c&l[Server]: %m&r&c muted you for %t!"
          staff: "&e&l[Server]: &eYou muted %p&r&e for %t!"
        permanent:
          player: "&c&l[Server]: %m&r&c muted you!"
          staff: "&e&l[Server]: &eYou muted %p&r&e!"

      # Message a player gets when he tries to chat while muted
      muted-chat:
        # Set unmutedate as %d
        temporary: "&c&l[Server]: &r&cYou are muted until %d!"
        permanent: "&c&l[Server]: &r&cYou are muted!"

    # Rank messages
    setrank:
      # Set staff as %m. Note that you will have to reset the color because of the prefix.
      # Set player as %p.
      # Set rank as %r.
      # Message a player gets when he is being promoted through /setrank
      promote:
        player: "&a&l[Server]: &r&aYou have been promoted to %r by %m&r&a!"
        staff: "&e&l[Server]: &r&eYou promoted %p to %r!"
      # Message a player gets when he is being demoted through /setrank
      demote:
        player: "&c&l[Server]: &r&aYou have been demoted to %r by %m&r&c!"
        staff: "&e&l[Server]: &r&eYou demoted %p to %r!"

    # Text above and below the tablist
    tablist:
      enabled: true
      # Set username as %u.
      # Set plugin version as %v.
      header: "&6&l --- Welcome %u --- "
      footer: "&6Running MXE V.%v"

    # Error messages players get when performing a command
    error:
      unsufficient-permissions: "&c&l[Server]:&r&c You don't have permissions to do that!"
      # Set syntax of command as %s
      syntax: "&6&l[Server]:&r&6 Syntax error: %s"
      target-not-found: "&c&l[Server]:&r&c Player not found!"
      other: "&c&l[Server]:&r&c An error occured while performing this command."

# Configuration and tweaks of commands
# Will contain things like max homes or disabled commands in the future
# Doesn't do anything yet
commands:
  # Disabled commands. Seperate by comma e.g. [ nick, vanish ]
  disabled: [  ]

  # Configuration of /home command
  home:
    # Maximum amount of homes a group can have
    # Default: 10
    max-homes:
      default: 10
      # Add your groups here. If a group is not found the plugin will use the default value

    # Time until player gets teleported in seconds.
    # Default: 0
    tp-time: 0

  tpaccept:
    # Time until player gets teleported in seconds.
    # Default: 0
    tp-time: 0

  help:
    # Wether or not the plugin replaces the vanilla /help command with it's own.
    # If set to false the plugin /help command can be called with /mxe help
    # Default: true
    replace-vanilla: true