name: MXE
version: '${project.version}'
main: me.mgsmemebook.mxe.MXE
description: Minecraft Spigot 1.19.2 Essentials Plugin
authors: [ mgsmemebook ]
website: https://github.com/mgsmemebook/MXE
api-version: 1.19
load: POSTWORLD
depend: [ LuckPerms ]
softdepend: [ ProtocolLib ]
commands:
  back:
    description: Return to your death location.
    usage: /help <command>

  ban:
    description: Ban a player.
    usage: /help <command>

  enderchest:
    description: Open your enderchest.
    usage: /help <command>
    aliases: [ ec, echest ]

  fly:
    description: Become an AH-64 Apache Attack Helicopter.
    usage: /help <command>

  gm:
    description: Change your gamemode.
    usage: /help <command>

  god:
    description: Become a god.
    usage: /help <command>

  help:
    description: This command.
    usage: /help

  mxe:
    description: This command.
    usage: /mxe

  home:
    description: Configure your homes.
    usage: /help <command>

  kick:
    description: Kick a player from the server.
    usage: /help <command>

  kill:
    description: Kill a player.
    usage: /help <command>

  mute:
    description: Mute a player.
    usage: /help <command>

  nick:
    description: Disguise yourself.
    usage: /help <command>

  pm:
    description: Send a private message to a player.
    usage: /help <command>

  reply:
    description: Send a private message to a player.
    usage: /help <command>
    alias: re

  setrank:
    description: Set a player's rank.
    usage: /help <command>

  tpa:
    description: Teleport to your friends.
    usage: /help <command>

  tpaccept:
    description: Accept the last tp-request.
    usage: /help <command>

  tpahere:
    description: Teleport a friend to you.
    usage: /help <command>

  tpall:
    description: Teleport all players to you.
    usage: /help <command>

  tpdeny:
    description: Reject the last tp-request.
    usage: /help <command>

  tphere:
    description: Teleport a player to you.
    usage: /help <command>

  unban:
    description: Forgive a player.
    usage: /help <command>

  unmute:
    description: Unmute a player.
    usage: /help <command>

  vanish:
    description: Disappear.
    usage: /help <command>
    aliases: van

permissions:
  mxe.*:
    default: false
    children:
      mxe.back: true
      mxe.ban: true
      mxe.enderchest: true
      mxe.fly: true
      mxe.gm: true
      mxe.god: true
      mxe.help: true
      mxe.home: true
      mxe.kick: true
      mxe.kill: true
      mxe.mute: true
      mxe.nick: true
      mxe.pm: true
      mxe.reply: true
      mxe.setrank: true
      mxe.tpa: true
      mxe.tpahere: true
      mxe.tpall: true
      mxe.tphere: true
      mxe.unban: true
      mxe.unmute: true
      mxe.vanish: true

  mxe.back:
    default: true

  mxe.ban:
    default: false

  mxe.enderchest:
    default: true

  mxe.fly:
    default: false

  mxe.gm:
    default: false

  mxe.god:
    default: false

  mxe.help:
    default: true

  mxe.home:
    default: true

  mxe.kick:
    default: false

  mxe.kill:
    default: false

  mxe.mute:
    default: false

  mxe.nick:
    default: false

  mxe.pm:
    default: true

  mxe.reply:
    default: true

  mxe.setrank:
    default: false

  mxe.tpa:
    default: true

  mxe.tpahere:
    default: true

  mxe.tpall:
    default: false

  mxe.tphere:
    default: false

  mxe.unban:
    default: false

  mxe.unmute:
    default: false

  mxe.vanish:
    default: false
