name: MXE
version: 1.3.1
main: me.mgsmemebook.mxe.MXE
description: Minecraft Spigot 1.19.2 Essentials Plugin
authors: [ mgsmemebook ]
website: https://github.com/mgsmemebook/MXE
api-version: 1.19
load: STARTUP
depend: [ LuckPerms ]
softdepend: [ ProtocolLib ]
commands:
  back:
    description: Kehre an deinen Todespunkt zurück.
    usage: /help <command>

  ban:
    description: Banne einen Spieler.
    usage: /help <command>

  fly:
    description: Werde zu einem AH-64 Apache Attack Helicopter.
    usage: /help <command>

  gm:
    description: Wechsle deinen Gamemode.
    usage: /help <command>

  god:
    description: Werde zum Gott.
    usage: /help <command>

  help:
    description: Dieser Befehl.
    usage: /help
    aliases: mxe help

  home:
    description: Verwalte deine Homes.
    usage: /help <command>

  kick:
    description: Kicke einen Spieler vom Server.
    usage: /help <command>

  kill:
    description: Töte einen Spieler.
    usage: /help <command>

  mute:
    description: Stumme einen Spieler.
    usage: /help <command>

  nick:
    description: Ändere deine Identität.
    usage: /help <command>

  setrank:
    description: Setze den Rang eines Spielers.
    usage: /help <command>

  tpa:
    description: Teleportiere dich zu deinen Freunden.
    usage: /help <command>

  tpaccept:
    description: Akzeptiere die letzte tp-Anfrage.
    usage: /help <command>

  tpahere:
    description: Teleportiere einen Freund zu dir.
    usage: /help <command>

  tpall:
    description: Teleportiere alle Spieler zu dir.
    usage: /help <command>

  tpdeny:
    description: Lehne die letzte tp-Anfrage ab.
    usage: /help <command>

  tphere:
    description: Teleportiere einen Spieler zu dir.
    usage: /help <command>

  unban:
    description: Vergebe einem Spieler.
    usage: /help <command>

  unmute:
    description: Entmute einen Spieler.
    usage: /help <command>

  vanish:
    description: Tauche unter.
    usage: /help <command>
    aliases: van

permissions:
  mxe.*:
    default: false
    children:
      mxe.back: true
      mxe.ban: true
      mxe.fly: true
      mxe.gm: true
      mxe.god: true
      mxe.help: true
      mxe.home: true
      mxe.kick: true
      mxe.kill: true
      mxe.mute: true
      mxe.nick: true
      mxe.setrank: true
      mxe.tpa: true
      mxe.tpahere: true
      mxe.tpall: true
      mxe.tphere: true
      mxe.unban: true
      mxe.unmute: true
      mxe.vanish: true

  mxe.back:
    default: true

  mxe.ban:
    default: false

  mxe.fly:
    default: false

  mxe.gm:
    default: false

  mxe.god:
    default: false

  mxe.help:
    default: true

  mxe.home:
    default: true

  mxe.kick:
    default: false

  mxe.kill:
    default: false

  mxe.mute:
    default: false

  mxe.nick:
    default: false

  mxe.setrank:
    default: false

  mxe.tpa:
    default: true

  mxe.tpahere:
    default: true

  mxe.tpall:
    default: false

  mxe.tphere:
    default: false

  mxe.unban:
    default: false

  mxe.unmute:
    default: false

  mxe.vanish:
    default: false
